WebApplicationDemo/Controllers/AjaxController.cs
using Business.Contracts;
using Entities;
using Microsoft.AspNetCore.Mvc;
using WebApplicationDemo.Models;

namespace WebApplicationDemo.Controllers
{


    public class AjaxController : Controller
    {
        public IMessageBusiness messageBusiness;

        public AjaxController(IMessageBusiness messageBusiness)
        {
            this.messageBusiness = messageBusiness;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> GetPerson(string name)
        {

            return Json(new { Name = name });
        }
        public async Task<IActionResult> GetRandomVC(int min, int max)
        {
            return ViewComponent("Random", new { min, max });
        }

        [HttpPost]
        public async Task<IActionResult> Search(string name)
        {
            var messages = await messageBusiness.GetMessagesAsync();

            var filteredMessages = messages.Where(m => m.Emeteur == name).ToList();
            

            //Mieux de creer un  VC qui organise l'affichage des messages
            //Là ça ne marchera pas
            //return Json si Api donc pas de vue
            return View("GetMessages",filteredMessages);

        }


    }
}

WebApplicationDemo/Controllers/Exo1Controller.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using System.Text.Json;
using WebApplicationDemo.Models;

namespace WebApplicationDemo.Controllers
{
    public class Exo1Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        //[HttpPost]
        //public string ApiTest()
        //{
        //    var mess = new Message() { Contenu = "aaaa" };
        //    return JsonSerializer.Serialize(mess);
        //}
        
        public IActionResult TestData()
        {
            TempData["TestKey"] = "Valeur du testKey";
            ViewBag.TestKey = "Valeur du ViewBag";
            return View();
        }

        public IActionResult TestData2()
        {
            TempData["TestKey"] = "Valeur du testKey 2";
            ViewBag.TestKey = "Valeur du ViewBag 2";
            return RedirectToAction("TestData");
        }

        public IActionResult TestData3()
        {
            TempData["TestKey"] = "Valeur du testKey 3";
            ViewBag.TestKey = "Valeur du ViewBag 3";
            return RedirectToAction("TestData2");
        }

        public IActionResult TestData4()
        {
            TempData["TestKey"] = "Valeur du testKey 4";
            ViewBag.TestKey = "Valeur du ViewBag 4";
            return View("TestData");
        }

    }
}

WebApplicationDemo/Controllers/Exo2Controller.cs
//using Entities;
using Entities;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using WebApplicationDemo.Models;

namespace WebApplicationDemo.Controllers
{
    public class Exo2Controller : Controller
    {
        static List<Message> messages = new()
        {
            new Message()
            {
                Id= 1,
                Contenu = "Contenu 1",
                Date = "01/01/2000",
                Emeteur="Emet 1"
            },new Message()
            {
                Id= 2,
                Contenu = "Contenu 2",
                Date = "02/02/2010",
                Emeteur="Emet 2"
            },new Message()
            {
                Id= 3,
                Contenu = "Contenu 3",
                Date = "03/03/2020",
                Emeteur="Emet 3"
            },
         };

        //Get
        [HttpGet]
        public IActionResult GetMessages()
        {
            return View(messages);
        }
        [HttpGet]
        public IActionResult GetMessage(int id)
        {
            var mess = messages.FirstOrDefault(m => m.Id == id);
            return View(mess);
        }


        //Add
        [HttpGet]
        public IActionResult AddMessage()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddMessage(Message message)
        {
            message.Id = messages.Count + 1;

            messages.Add(message);

            return RedirectToAction("GetMessage", new { Id = message.Id });
        }

        //Delete
        [HttpGet]
        public IActionResult DeleteMessage(int messId)
        {
            messages.Remove(messages.FirstOrDefault(m => m.Id == messId));

            TempData["info"] = "Message supprimé";
            return RedirectToAction("GetMessages");
        }

        //Update
        [HttpGet]
        public IActionResult EditMessage(int messId)
        {
            Message mess = messages.FirstOrDefault(m => m.Id == messId);
            return View(mess);

        }

        [HttpPost]
        public IActionResult EditMessage(int id, string contenu)
        {
            TempData["info"] = "Message modifié";

            Message mess = messages.FirstOrDefault(m => m.Id == id);
            mess.Contenu = contenu;

            return RedirectToAction("GetMessage", new { Id = id });
        }


    }
}

WebApplicationDemo/Controllers/Exo3Controller.cs
//using Entities;
using Entities;
using Microsoft.AspNetCore.Mvc;
using WebApplicationDemo.Models;

namespace WebApplicationDemo.Controllers
{
    public class Exo3Controller : Controller
    {
        static List<Message> messages = new()
        {
            new Message()
            {
                Id= 1,
                Contenu = "Contenu 1",
                Date = "01/01/2000",
                Emeteur="Emet 1"
            },new Message()
            {
                Id= 2,
                Contenu = "Contenu 2",
                Date = "02/02/2010",
                Emeteur="Emet 2"
            },new Message()
            {
                Id= 3,
                Contenu = "Contenu 3",
                Date = "03/03/2020",
                Emeteur="Emet 3"
            },
         };

        [HttpGet]
        public IActionResult GetMessagePV(int id)
        {
            var mess = messages.FirstOrDefault(m=>m.Id==id);
            return View(mess);
        }

        [HttpGet]
        public IActionResult GetMessageListPV()
        {
            return View(messages);
        }

        [HttpGet]  
        public IActionResult GetListInt()
        {
            return View();
        }


    }
}

WebApplicationDemo/Views/Shared/_GetMessage.cshtml
@model Message

<div>
    <p>Emetteur : @Model.Emeteur</p>
    <p>Contenu : @Model.Contenu</p>
    <p>Date : @Model.Date</p>
</div>

WebApplicationDemo/Views/Shared/_GetMessagelist.cshtml
@model List<Message>



@foreach (var message in Model)
{
    <p>Message ID = @message.Id</p>
    <p>@message.Emeteur : @message.Contenu, fait le @message.Date</p>

    <a class="btn btn-primary" asp-action="GetMessagePV" asp-route-id="@message.Id">Details</a>
    
}

WebApplicationDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplicationDemo.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplicationDemo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exo1" asp-action="TestData">TestData</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exo1" asp-action="TestData2">TestData2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exo1" asp-action="TestData3">TestData3</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exo1" asp-action="TestData4">TestData4</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exo2" asp-action="GetMessages">Messages</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exo2" asp-action="AddMessage">Formulaire</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exo3" asp-action="GetMessagePV" asp-route-Id="2">Message en PV</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exo3" asp-action="GetMessageListPV">Liste de message en PV</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exo3" asp-action="GetListInt">Liste de int component</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exo4" asp-action="GetRandom">Random with VC</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exo5" asp-action="AddMessage">Formulaire Exo5</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ajax" asp-action="Index">Ajax Test</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplicationDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
</body>
</html>