WebApplicationDemo/Controllers/Exo3Controller.cs
//using Entities;
using Entities;
using Microsoft.AspNetCore.Mvc;
using WebApplicationDemo.Models;

namespace WebApplicationDemo.Controllers
{
    public class Exo3Controller : Controller
    {
        static List<Message> messages = new()
        {
            new Message()
            {
                Id= 1,
                Contenu = "Contenu 1",
                Date = "01/01/2000",
                Emeteur="Emet 1"
            },new Message()
            {
                Id= 2,
                Contenu = "Contenu 2",
                Date = "02/02/2010",
                Emeteur="Emet 2"
            },new Message()
            {
                Id= 3,
                Contenu = "Contenu 3",
                Date = "03/03/2020",
                Emeteur="Emet 3"
            },
         };

        [HttpGet]
        public IActionResult GetMessagePV(int id)
        {
            var mess = messages.FirstOrDefault(m=>m.Id==id);
            return View(mess);
        }

        [HttpGet]
        public IActionResult GetMessageListPV()
        {
            return View(messages);
        }

        [HttpGet]  
        public IActionResult GetListInt()
        {
            return View();
        }


    }
}

WebApplicationDemo/ViewComponents/RangeIntViewComponent.cs
using Business.Services;
using Microsoft.AspNetCore.Mvc;

namespace WebApplicationDemo.ViewComponents
{
    public class RangeIntViewComponent : ViewComponent
    {
        private readonly IRandomGenService _randomGenService;

        public RangeIntViewComponent(IRandomGenService randomGenService)
        {
            _randomGenService = randomGenService;
        }
        public IViewComponentResult Invoke(int min, int max)
        {
            var num = _randomGenService.GetRandom(min, max);

            List<int> values = new() { min, num, max };

            return View(values);
        }

    }
}

WebApplicationDemo/Views/Exo3/GetListInt.cshtml
<h1>Min|Rand|Max</h1>

<div>
    <vc:range-int min="10" max="100"/>
 </div>

WebApplicationDemo/Views/Exo3/GetMessageListPV.cshtml
@model List<Message>

<h1><strong>Liste de messages avec la vue partielle</strong></h1>

<div>
    <partial name="_GetMessageList"></partial>
</div>

WebApplicationDemo/Views/Exo3/GetMessagePV.cshtml
@model Message

<h1><strong>Message avec la vue partielle</strong></h1>

<div>
    <partial name="_GetMessage"></partial>
</div>